### ISSUE TITLE
 how to use the topologyLayer to classify MNIST dataset

### ISSUE THREAD

**Issue by changshuowang** [bruel-gabrielsson/TopologyLayer#20]
Hello, the paper mentions using the topologyLayer to classify MNIST dataset. Where can I find this part of the code?

**Comment by bnels** [comment]
Hi @changshuowang, the code that ran these experiments hasn't been ported to the repository yet.  We hope to do this soon.  In the mean time, the features we used are described in section 3.3 of https://arxiv.org/abs/1905.12200, which should allow you to run your own experiment.

We'll keep this issue open until we have examples added.

**Comment by changshuowang** [comment]
OK&nbsp;!&nbsp;Thank&nbsp;you&nbsp;for&nbsp;your&nbsp;reply&nbsp;and&nbsp;Looking&nbsp;forward&nbsp;to&nbsp;seeing&nbsp;your&nbsp;work&nbsp;as&nbsp;soon&nbsp;as&nbsp;possible.
Another&nbsp;question,&nbsp;how&nbsp;can&nbsp;I&nbsp;use&nbsp;LeverSetLayer2D&nbsp;to&nbsp;process&nbsp;three&nbsp;channel&nbsp;color&nbsp;images?


---Original---

**Comment by changshuowang** [comment]
OK ! Thank you for your reply and Looking forward to seeing your work as soon as possible.
Another question, how can I use LeverSetLayer2D to process three channel color images?

**Comment by bnels** [comment]
@changshuowang for three-channel images, you would need to know what sort of filtration you would like to use.  One option might be treating it as a 3d image with a levelset filtration, but there's an issue with interpretability here.  Another might be to process to a single-channel 2d image through a grayscale map (you can make this differentiable! e.g. 1x1 convolution + sigmoid) and then using LevelSetLayer2D.  Or you could do each channel separately and combine features, or focus on one channel, or use multiple differentiable grayscale maps.  This will all be dependent on what you'd like to capture using persistent homology.

**Comment by changshuowang** [comment]
> @changshuowang for three-channel images, you would need to know what sort of filtration you would like to use. One option might be treating it as a 3d image with a levelset filtration, but there's an issue with interpretability here. Another might be to process to a single-channel 2d image through a grayscale map (you can make this differentiable! e.g. 1x1 convolution + sigmoid) and then using LevelSetLayer2D. Or you could do each channel separately and combine features, or focus on one channel, or use multiple differentiable grayscale maps. This will all be dependent on what you'd like to capture using persistent homology.

**Comment by changshuowang** [comment]
@bnels Thank you for reply.

**Comment by xchhuang** [comment]
Hi @bnels,

I am also interested in section 3.3 topological attacks, about the directional sweeps. 

Does it mean that we simply change the pixel values considering their corresponding image coordinates ? Also, I am wondering if the directional sweeps can also be used for 2D point cloud to extract directional features? Thanks in advance.
