### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by AjeyPaiK** [bruel-gabrielsson/TopologyLayer#23]
I tried installing the topologylayer using pip. Here is the error that I get:

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-j7_txq74-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wskt075y-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-j7_txq74-build/

Edit: I have already tried sudo apt-get install python3-dev. It did not work for me

**Comment by AjeyPaiK** [comment]
(IMPORTANT UPDATE):

I solved the issue by downgrading my pytorch. It seems, this repo is not compatible with Pytorch 1.5 (which was the latest version of pytorch when I encountered this error).

**Comment by ulupo** [comment]
I encountered the same issue, with the same fix (downgrading to `pytorch` 1.4). In my case, it seemed related to `pytorch` 1.5 requiring `C++14` standards.
